apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      serviceAccountName: clo835
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: flask-app
        image: 562183160408.dkr.ecr.us-east-1.amazonaws.com/webapp-repo
        ports:
        - containerPort: 81
        env:
        - name: IMAGE_URL
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: IMAGE_URL
        - name: USER_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: USER_NAME
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DBUSER
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DBPWD
        - name: DATABASE
          value: employees
        - name: DBHOST
          value: mysql-0.mysql-headless.final.svc.cluster.local
        - name: DBPORT
          value: "3306"
        - name: APP_COLOR
          value: blue
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SESSION_TOKEN
